<?xml version="1.0"?>
<package format="3">
  <name>cooperative_transport_gazebo</name>
  <version>0.1.0</version>
  <description>Gazebo Fortress world and bridges for AMIR cooperative transport.</description>
  <maintainer email="dars5070@todo.todo">dars5070</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <build_depend>ignition-gazebo6</build_depend>
  <exec_depend>ros_gz_bridge</exec_depend>
  <exec_depend>ros_gz_interfaces</exec_depend>
  <exec_depend>ros_gz_sim</exec_depend>
  <exec_depend>rosgraph_msgs</exec_depend>
  <exec_depend>std_msgs</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
