<?xml version="1.0"?>
<package format="3">
  <name>cooperative_transport_bringup</name>
  <version>0.1.0</version>
  <description>Integrated two-AMIR cooperative transport simulation launch.</description>
  <maintainer email="dars5070@todo.todo">dars5070</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>amir_gazebo</exec_depend>
  <exec_depend>cooperative_transport_control</exec_depend>
  <exec_depend>cooperative_rotation</exec_depend>
  <exec_depend>cooperative_transport_description</exec_depend>
  <exec_depend>cooperative_transport_gazebo</exec_depend>
  <exec_depend>coop_transport_bt</exec_depend>
  <exec_depend>coop_transport_controller</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>ros_gz_bridge</exec_depend>
  <exec_depend>ros_gz_sim</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
